[program:awesometuringmachine]
directory = /home/tao/web_app/awesometuringmachine
user = tao
command = /home/tao/.rbenv/versions/1.9.3-p125/bin/ruby /home/tao/.rbenv/versions/1.9.3-p125/bin/thin start -e production -S ./tmp/thin.sock
redirect_stderr = true
stderr_logfile = none
autostart = true
autorestart = true